CFLAGS=-Wall -m32 -g -O0

BINARIES=pointers hex2bin bin2hex caesar_cipher  has_address oneplusone binary_count_01 binary_count_02 binary_count_03 binary_count_04 break_caesar_cipher modulo_01 modulo_02 modulo_03

all:${BINARIES}

clean:
	rm -f ${BINARIES}

